In [2]:
# Step 1: Import libraries
import pandas as pd
import numpy as np

# Step 2: Load the dataset
df = pd.read_csv('C:/Users/Priyanka Yadav/Downloads/survey (1).csv')  # Replace with your actual filename
df.head()


Timestamp  Age  Gender         Country state self_employed  \
0  2014-08-27 11:29:31   37  Female   United States    IL           NaN   
1  2014-08-27 11:29:37   44       M   United States    IN           NaN   
2  2014-08-27 11:29:44   32    Male          Canada   NaN           NaN   
3  2014-08-27 11:29:46   31    Male  United Kingdom   NaN           NaN   
4  2014-08-27 11:30:22   31    Male   United States    TX           NaN   

  family_history treatment work_interfere    no_employees  ...  \
0             No       Yes          Often            6-25  ...   
1             No        No         Rarely  More than 1000  ...   
2             No        No         Rarely            6-25  ...   
3            Yes       Yes          Often          26-100  ...   
4             No        No          Never         100-500  ...   

                leave mental_health_consequence phys_health_consequence  \
0       Somewhat easy                        No                      No   
1          Don't know                     Maybe                      No   
2  Somewhat difficult                        No                      No   
3  Somewhat difficult                       Yes                     Yes   
4          Don't know                        No                      No   

      coworkers supervisor mental_health_interview phys_health_interview  \
0  Some of them        Yes                      No                 Maybe   
1            No         No                      No                    No   
2           Yes        Yes                     Yes                   Yes   
3  Some of them         No                   Maybe                 Maybe   
4  Some of them        Yes                     Yes                   Yes   

  mental_vs_physical obs_consequence comments  
0                Yes              No      NaN  
1         Don't know              No      NaN  
2                 No              No      NaN  
3                 No             Yes      NaN  
4         Don't know              No      NaN  

[5 rows x 27 columns]

steps to clean 

In [4]:
# Step 3: Drop unnecessary columns (example)
df = df.drop(['Timestamp', 'comments'], axis=1, errors='ignore')


In [5]:
# Step 4: Handle missing values
df = df.dropna()  # or fillna if appropriate


In [6]:
# Step 4: Handle missing values
df = df.dropna()  # or fillna if appropriate


In [7]:
# Step 5: Encode categorical variables
from sklearn.preprocessing import LabelEncoder

label_encoders = {}
for column in df.select_dtypes(include='object').columns:
    le = LabelEncoder()
    df[column] = le.fit_transform(df[column])
    label_encoders[column] = le


In [8]:
# Step 6: Split into features and target
X = df.drop('treatment', axis=1)
y = df['treatment']


In [9]:
# Step 7: Split into train and test sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [10]:
# Step 8: Train a classifier
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)


RandomForestClassifier(random_state=42)

In [9]:
# Step 9: Save model and encoders
import joblib

joblib.dump(model, 'model.pkl')
joblib.dump(label_encoders, 'label_encoders.pkl')


['label_encoders.pkl']

#Predict whether a person is likely to seek mental health treatment based on survey responses.
# Target column: 'treatment'
# Type: Binary classification (0 = No, 1 = Yes)


In [11]:
#Split the Dataset
from sklearn.model_selection import train_test_split
X = df.drop('treatment', axis=1)
y = df['treatment']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [12]:
# Select model
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(random_state=42)


In [13]:
# Train model
model.fit(X_train, y_train)


RandomForestClassifier(random_state=42)

In [14]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Split dataset
X = df.drop('treatment', axis=1)
y = df['treatment']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train model
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

# Predict
y_pred = model.predict(X_test)

# Evaluate
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))


Accuracy: 0.7526881720430108
Confusion Matrix:
 [[18 17]
 [ 6 52]]
Classification Report:
               precision    recall  f1-score   support

           0       0.75      0.51      0.61        35
           1       0.75      0.90      0.82        58

    accuracy                           0.75        93
   macro avg       0.75      0.71      0.71        93
weighted avg       0.75      0.75      0.74        93



In [15]:
from sklearn.model_selection import GridSearchCV

params = {'n_estimators': [100, 150], 'max_depth': [None, 10, 20]}
grid = GridSearchCV(RandomForestClassifier(random_state=42), param_grid=params, cv=5)
grid.fit(X_train, y_train)

model = grid.best_estimator_


In [16]:
final_preds = model.predict(X_test)
print("Final Accuracy:", accuracy_score(y_test, final_preds))


Final Accuracy: 0.7526881720430108


In [17]:
from sklearn.preprocessing import StandardScaler

# Fit scaler on training data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Optionally update X_train and X_test
X_train = X_train_scaled
X_test = X_test_scaled


In [18]:
import joblib

joblib.dump(model, 'rmodel.pkl')
joblib.dump(label_encoders, 'label_encoders.pkl')
joblib.dump(scaler, 'rscaler.pkl')


['rscaler.pkl']

In [19]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Accuracy
print("✅ Accuracy:", accuracy_score(y_test, y_pred))

# Confusion matrix
print("✅ Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

# Full classification report
print("✅ Classification Report:\n", classification_report(y_test, y_pred))


✅ Accuracy: 0.7526881720430108
✅ Confusion Matrix:
 [[18 17]
 [ 6 52]]
✅ Classification Report:
               precision    recall  f1-score   support

           0       0.75      0.51      0.61        35
           1       0.75      0.90      0.82        58

    accuracy                           0.75        93
   macro avg       0.75      0.71      0.71        93
weighted avg       0.75      0.75      0.74        93



In [20]:
pip install imbalanced-learn


Note: you may need to restart the kernel to use updated packages.


In [21]:
from imblearn.over_sampling import SMOTE

# Apply SMOTE only to training data
smote = SMOTE(random_state=42)
X_train_bal, y_train_bal = smote.fit_resample(X_train, y_train)

print("Before SMOTE:", y_train.value_counts())
print("After SMOTE:", y_train_bal.value_counts())


Before SMOTE: treatment
1    255
0    116
Name: count, dtype: int64
After SMOTE: treatment
1    255
0    255
Name: count, dtype: int64


In [22]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(random_state=42)
model.fit(X_train_bal, y_train_bal)


RandomForestClassifier(random_state=42)

In [23]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

y_pred = model.predict(X_test)

print("✅ Accuracy:", accuracy_score(y_test, y_pred))
print("✅ Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("✅ Classification Report:\n", classification_report(y_test, y_pred))


✅ Accuracy: 0.7311827956989247
✅ Confusion Matrix:
 [[17 18]
 [ 7 51]]
✅ Classification Report:
               precision    recall  f1-score   support

           0       0.71      0.49      0.58        35
           1       0.74      0.88      0.80        58

    accuracy                           0.73        93
   macro avg       0.72      0.68      0.69        93
weighted avg       0.73      0.73      0.72        93



In [37]:
df.to_csv('cleaned_dataset.csv', index=False)


In [24]:

import joblib

# Save model
joblib.dump(model, 'rmodel.pkl')

# Save scaler if used
joblib.dump(scaler, 'rscaler.pkl')

# Save encoders if used for categorical features
joblib.dump(label_encoders, 'label_encoders.pkl')


['label_encoders.pkl']

In [25]:
import os
print(os.getcwd())


C:\Users\Priyanka Yadav


In [26]:
import joblib

# Save the trained model
joblib.dump(model, 'rmodel.pkl')

# Save the scaler (only if it was defined)
joblib.dump(scaler, 'rscaler.pkl')

# Save the label encoders (this should be a dictionary)
joblib.dump(label_encoders, 'label_encoders.pkl')


['label_encoders.pkl']

In [27]:
import os
print("Saving in folder:", os.getcwd())


Saving in folder: C:\Users\Priyanka Yadav


In [28]:
joblib.dump(model, 'rmodel.pkl')


['rmodel.pkl']

In [29]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()
model.fit(X_train, y_train)  # Replace with your data

# Now save
joblib.dump(model, 'rmodel.pkl')


['rmodel.pkl']

In [38]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import joblib

# 1. Load your dataset
df = pd.read_csv('cleaned_dataset.csv')  # Replace with your actual file

# 2. Separate features and target
X = df.drop('treatment', axis=1)
y = df['treatment']

# 3. Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 4. Save the feature names from training data
trained_features = list(X_train.columns)
joblib.dump(trained_features, 'trained_feature_names.pkl')

# 5. Fit the scaler and save it
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
joblib.dump(scaler, 'scaler.pkl')

# 6. Train your model (example: Logistic Regression)
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train_scaled, y_train)

# 7. Save the model
joblib.dump(model, 'model.pkl')


['model.pkl']

In [39]:
joblib.dump(X.columns.tolist(), 'feature_columns.pkl')


['feature_columns.pkl']